---
- name: Install Clickhouse
  hosts: localhost
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  tasks:
    - block:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/deb/pool/main/c/{{ item }}/{{ item }}_{{ clickhouse_version }}_amd64.deb"
            dest: "./{{ item }}-{{ clickhouse_version }}_amd64.deb"
          with_items: "{{ clickhouse_packages }}"
      rescue:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/deb/pool/main/c/clickhouse-common-static/clickhouse-common-static_{{ clickhouse_version }}_amd64.deb"
            dest: "./clickhouse-common-static_{{ clickhouse_version }}_amd64.deb"
    - name: Install clickhouse packages
      become: true
      ansible.builtin.apt:
        deb: "/home/siz/ansible_hw2/{{ item.1 }}"
      with_indexed_items:
        - clickhouse-common-static-{{ clickhouse_version }}_amd64.deb
        - clickhouse-client-{{ clickhouse_version }}_amd64.deb
        - clickhouse-server-{{ clickhouse_version }}_amd64.deb
      notify: Start clickhouse service
    - name: Flush handlers
      meta: flush_handlers
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0

- name: Install and configure Vector
  hosts: localhost
  become: true
  tasks:
    - name: Get vector distrib
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/0.39.0/vector_0.39.0-1_amd64.deb"
        dest: "./vector_0.39.0-1_amd64.deb"
    - name: Install clickhouse packages
      ansible.builtin.apt:
        deb: "/home/siz/ansible_hw2/vector_0.39.0-1_amd64.deb"

    - name: Deploy Vector configuration
      template:
        src: templates/vector.toml.j2
        dest: /etc/vector/vector.toml
        owner: root
        group: root
        mode: '0644'
      notify: restart vector
      tags: config

  handlers:
    - name: restart vector
      service:
        name: vector
        state: restarted
- name: Install Lighthouse and Nginx
  hosts: localhost
  become: true
  tasks:
    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Download Lighthouse
      ansible.builtin.get_url:
        url: "https://github.com/VKCOM/lighthouse/archive/refs/heads/master.zip"
        dest: "/tmp/lighthouse.tar.gz"

    - name: Extract Lighthouse
      ansible.builtin.unarchive:
        src: "/tmp/lighthouse.tar.gz"
        dest: "/var/www/html/lighthouse"
        remote_src: true

    - name: Configure Nginx for Lighthouse
      ansible.builtin.copy:
        content: |
          server {
              listen 8081;
              server_name localhost;

              location / {
                  root /var/www/html/lighthouse/lighthouse-master;
                  index index.html;
              }
          }
        dest: /etc/nginx/conf.d/lighthouse.conf
        owner: root
        group: root
        mode: '0644'

    - name: Enable Lighthouse Nginx configuration
      ansible.builtin.file:
        src: /etc/nginx/sites-available/lighthouse
        dest: /etc/nginx/sites-enabled/lighthouse
        state: link

    - name: Remove default Nginx configuration
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Restart Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted