{
 "title": "some new dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU LA 1m",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "CPU LA 5M",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "CPU LA 15M",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "Утилизация CPU (в процентах, 100-idle)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{job=\"nodeexporter\", mode=\"idle\"}[5m])) * 100)\r\n"
    }
   ]
  },
  {
   "title": "FREE MEM %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{job=\"nodeexporter\"} / 1024 / 1024 /1024"
    }
   ]
  },
  {
   "title": "FREE SPACE",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 10, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{job=\"nodeexporter\",fstype!~\"tmpfs|fuse.lxcfs|squashfs\"} / 1024 / 1024 / 1024\r\n"
    }
   ]
  }
 ]
}