apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: test
  ports:
    - name: nginx
      protocol: TCP
      port: 80
      nodePort: 30001
    - name: multi
      protocol: TCP
      port: 8080
      nodePort: 30002
  type: NodePort