apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: test
  ports:
    - name: nginx
      protocol: TCP
      port: 9001
      targetPort: 80
    - name: multi
      protocol: TCP
      port: 9002
      targetPort: 8080
